### ISSUE TITLE
Status Update

### ISSUE THREAD

**Issue by E3V3A** [wapiflapi/veles#3]
@wapiflapi 
Hey! This look awesome.
I just found this place in a very roundabout way. What is the current status of the project?

**Comment by wapiflapi** [comment]
Hey, thank you for the interest!

This is / was a fork of https://github.com/codilime/veles where I added a lot of my ideas from https://github.com/wapiflapi/binglide and some projections the original didn't have.

I haven't looked at this in a while so I don't know how things evolved upstream and how much of what is here has been adopted up stream. But I definitely suggest you take a look at the original as I suspect it improved quiet a bit!

I guess the "status" of this project is nothing much. This fork is definitely not maintained and it's not kept up to pace with upstream.

If you want to discuss algorithms & code for this kind of data type visualisations so you can contribute yourself feel free to start a conversation :-)

**Comment by E3V3A** [comment]
Aha, I see! Great and thank you so much for super quick reply!  :+1: 
I just had a look and it seem that not too much has happened since May last year...
Thanks and cheers. :)

PS. I also looked at some of your other repos, which also look very interesting.
